name: Tests

on:
  - push
  - pull_request

jobs:
  test-clang-gcc-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [clang++, gcc]
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    env:
      CC: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
        pip install tox-gh-actions
    - name: Test with tox
      run: tox
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev_requirements.txt
        pip install tox-gh-actions
    - name: Test with tox
      run: tox

